### ISSUE TITLE
Caffeine fails to start

### ISSUE THREAD

**Issue by skwerlman** [bmrf/tron#78]
```
The application has failed to start because its side-by-side configuration is incorrect.
Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

This occurs when running tron from both safe-mode and normal boot, and when running the .exe manually.

**Comment by vocatus** [comment]
Hi skwerlman,

Thanks for the report. I need some more information from you however. What version of Windows? What architecture? Log file?

**Comment by skwerlman** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I'm on windows 10 64-bit. Which specific logfile do you need, or should I zip all of them?

On April 17, 2016 9:49:56 AM EDT, Vocatus Gate <notifications@github.com> wrote:
>Hi skwerlman,
>
>Thanks for the report. I need some more information from you however.
>What version of Windows? What architecture? Log file?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bmrf/tron/issues/78#issuecomment-211021631
-----BEGIN PGP SIGNATURE-----

iQQ9BAEBCgAnIBxTa3dlcmxtYW4gPHNrd2VybG1hbkBnbWFpbC5jb20+BQJXE6WR
AAoJELShWUfEgpPyE5cgAJEEo4miHTExPVTLDJUSp8fETZY9H/GRgwIK6p5VHY5/
/SHH79L9WQu3QbHK/vxDd9tCntvRGbZaVFZEruQ8jGuevgWwikv31eOAKeB98h39
I8HKWUSmhHFQWqE4LsONCaFyewRTs/OOMKskhD8RbnPyoCJR6Oo/cB71rp3Oj5yl
qw1w0hJKLn9iTLvlg1NfEzLnRnr+EDJgc54mUo08BUAGXWhZH/Hm77LKRI/oTQFR
Sqs6/GTroOMKfY8R9I/lW3BzfK+uRzByZKhQq3rccHNAqh2IIoG4shmcPpRe6G59
l9w3FpiDkxujFtuEV1Y6mDtDisUc/0ke4/P1rY8s+yHTgtWOLuQmq9vhOGElueJP
mXpsjQra+rrEjMzHAs3W70y3x5Y77IAKl8CkqYDmgrVjWn4mV6iZJaonNwcc0NvQ
YeBx6yq1Wxb1gf/d8xZTRzeOfW2QwCArWQJYGMoJgijsmhHb89kz3mU38l1xYoCT
rH3o0eQhcmAgYbj68LBmDgprvDNTZbeb7hvGVLYpA2Y0rvzSp2ROj3QUlTGnkMEj
aoS1hhqcazjHbodLaii0CNZF30YKCdxKMze6Y+Kpa5INCdmpTaLthjlmsGOOPpcj
YmVvQw40xr2ROIqTfHvCurV1WQepEQD5VRAkBcOo6oOIyP462rTERUA9CN2BdgT7
vikK83x7T8BuiSr0b2x0lfrIcS5NJM+YkfxsZKMY4xeJp4rH+diSMv60S+zDEO4u
foUgZyIxIJE70kvQRI3U/YviM/IHwKukzhwwRXQx5tRJzg6gk8VGb2QDPLD050Ds
T+sC36riUkgyFe5KG8IbS4m5obYXWESs9+TI6OxcCuVTA+jKxUqJuRxSBdnffWuz
vlpYu2QSl+sEHOH/Jbpvdn3t2uUwBbYwXP8GpfIbOPfFBdmoOGwywnb7A9nR7kQZ
wGDP/NdYMQi+KdMpbTLazsFV4xMemdK4pQug8bqGjHnhCtOhEcNsOkAskZsJ40aB
2iAkOBQpUf/4wGn5sfZPMVfSkrSs611U6XS9yvECrTBG64cpDJ+qsKUNuTMLkaec
9M7btFZrzAQQomb8MZfnP0nVDEjVogd6iGtKXO0dtR0Sr/UKz7DJ5wlRwKwhKdOg
rToqZ32iWMJ0v8m6bbE/v/8lNisYDaHyt4FCOP+/D29qh8PoYDoHtVkziB8LZGnX
0RRSzkaivmfz9HAOulZWX62H2N1hUgJFJX5QWggwCXoiLtOtm51AldxpNTnTWOzh
Of4iYUGSgJYkpahKUttcTN8KjMTTAN+m4GvY5hlenlnx/M7rGGSLIY8Aka3WOMgR
ZmvFKEjN4d9zlscDeuNoN99+CYFtuRql16WFR9vI1+Q=
=oIe1
-----END PGP SIGNATURE-----

**Comment by vocatus** [comment]
`Tron.log` should be fine. 

I've seen it happen on a few Win10 hosts here as well, currently researching another method of keeping the system awake. Previously I'd written quite a bit of code to preserve the Power Scheme, then switch to Active (always on), then revert back to the old power scheme after Tron finished, but it didn't work 100% reliably and it was a big mess of code. Caffeine was a much, much simpler solution. 

Anyway, send the log files over. Just thought to post some background into the use of the utility.

**Comment by vocatus** [comment]
OK, I got in touch with the author of Caffeine, and apparently it's due to the Visual C++ 2008 runtimes not being installed. They're apparently present in varying versions of Windows, and missing in others.

http://www.zhornsoftware.co.uk/support/kb.pl?q=00085

So it's a known issue, and the resolution is to install the Visual C++ 2008 redistributable. 

Closing

**Comment by vocatus** [comment]
Hey skwerlman, just wanted to give you an update, Tom, the author of Caffeine, provided a statically-linked version of Caffeine for use in Tron, so it should resolve the issue. The updated binary will go out in the next release.

**Comment by skwerlman** [comment]
Oh, shoot; I missed these somehow. Thanks for the update; any idea which version that will be?

**Comment by vocatus** [comment]
v9.0.1, I'll probably push it out here in a week or so. I
      generally wait until there are at least a few bug fixes and tool
      updates before pushing a new version, especially right now because
      bandwidth is so expensive/slow here.
    
    
    On 2016-05-07 21:10, skwerlman wrote:
    
    
      Oh, shoot; I missed these somehow. Thanks for the update; any
        idea which version that will be?
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly or view
          it on GitHub

**Comment by andreasspindler** [comment]
Still not working with the latest version which should work on Win7-10.
